# Generated by Django 3.2.4 on 2021-06-21 09:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_Name', models.CharField(max_length=50)),
                ('family_Name', models.CharField(max_length=50)),
                ('qb_EmpId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('item_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryAddr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('postal_Code', models.CharField(max_length=10)),
                ('qb_Id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearer', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='TimeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('hours', models.IntegerField()),
                ('billable_Status', models.CharField(max_length=50)),
                ('hourly_Rate', models.IntegerField()),
                ('time_activity_id', models.IntegerField()),
                ('sync_token', models.IntegerField(default=0)),
                ('name_of', models.CharField(choices=[('Employee', 'Employee'), ('Vendor', 'Vendor')], default='Employee', max_length=10)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.employee')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.item')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='primaryAddr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.primaryaddr'),
        ),
    ]
