# Generated by Django 3.2.3 on 2021-06-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='primaryAddr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.primaryaddr'),
        ),
        migrations.AlterField(
            model_name='primaryaddr',
            name='qb_Id',
            field=models.IntegerField(null=True),
        ),
    ]
