# Generated by Django 3.2.3 on 2021-06-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210610_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fully_Qualified_Name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='time',
        ),
    ]
