# Generated by Django 3.2.3 on 2021-06-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210610_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Employee',
        ),
    ]
