# Generated by Django 3.2.3 on 2021-06-11 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_employee_timeactivity_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeactivity',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.employee'),
        ),
    ]
