# Generated by Django 3.2.3 on 2021-06-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_timeactivity_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeactivity',
            name='sync_token',
            field=models.IntegerField(default=0),
        ),
    ]
