# Generated by Django 3.2.4 on 2021-06-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_timeactivity_sync_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearer', models.CharField(max_length=10000)),
            ],
        ),
    ]
